[cockroach]
Host        = "localhost"
Port        = "26257"
Password    = "go-micropass"
User        = "go-micro"
Database    = "go-microdb"

[nats]
User        = "product"
Password    = "gopher"
Queue       = "EVENT-QUEUE"
Name        = "Nats Requester"
WaitTimeInMins = 10