[cockroach]
Host        = "localhost"
Port        = "26257"
Password    = "eduwizpass"
User        = "eduwiz"
Database    = "eduwizdb"

[nats]
User        = "product"
Password    = "gopher"
Queue       = "PERSIST-STUDENT"
Name        = "Nats Responder"
WaitTimeInMinutes = 10