[cockroach]
Host        = "localhost"
Port        = "26257"
Password    = "go-micropass"
User        = "go-micro"
Database    = "go-microdb"

[nats]
URI         = "nats://nats:4222"
User        = "product"
Password    = "gopher"
Queue       = "RETRIEVE-STUDENTS"
Name        = "Nats Responder"
WaitTimeInMinutes = 10