// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	EventId              string   `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType            string   `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AggregateId          string   `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateType        string   `protobuf:"bytes,4,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	Data                 string   `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *Event) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *Event) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

func (m *Event) GetAggregateType() string {
	if m != nil {
		return m.AggregateType
	}
	return ""
}

func (m *Event) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "pb.Event")
	proto.RegisterType((*Response)(nil), "pb.Response")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xbd, 0x8a, 0xc3, 0x30,
	0x10, 0x84, 0xf1, 0xcf, 0x9d, 0xed, 0xf5, 0xdd, 0x15, 0x5b, 0xe9, 0x8a, 0x40, 0x62, 0x08, 0xa4,
	0x4a, 0x93, 0x67, 0x48, 0xe1, 0x56, 0xa4, 0x0f, 0xb2, 0xb5, 0x88, 0x14, 0xb1, 0x85, 0x57, 0x09,
	0xf8, 0x69, 0xf2, 0xaa, 0xc1, 0x1b, 0x6c, 0x77, 0x9a, 0xf9, 0x46, 0xc3, 0xb0, 0x50, 0xd2, 0x93,
	0xba, 0x70, 0xf4, 0x43, 0x1f, 0x7a, 0x8c, 0x7d, 0x53, 0xbd, 0x22, 0xf8, 0x3a, 0x4f, 0x1e, 0xfe,
	0x43, 0x2e, 0xf0, 0x7a, 0xb3, 0x2a, 0xda, 0x46, 0x87, 0x42, 0x67, 0xa2, 0x6b, 0x8b, 0x1b, 0x80,
	0x0f, 0x0a, 0xa3, 0x27, 0x15, 0x0b, 0x2c, 0xc4, 0xb9, 0x8c, 0x9e, 0x70, 0x07, 0x3f, 0xc6, 0xb9,
	0x81, 0x9c, 0x09, 0x34, 0xfd, 0x4e, 0x24, 0x50, 0x2e, 0x5e, 0x6d, 0x71, 0x0f, 0x7f, 0x6b, 0x44,
	0x5a, 0x52, 0x09, 0xfd, 0x2e, 0xae, 0x34, 0x21, 0xa4, 0xd6, 0x04, 0xa3, 0x32, 0x81, 0xf2, 0xae,
	0x34, 0xe4, 0x9a, 0xd8, 0xf7, 0x1d, 0x13, 0x2a, 0xc8, 0xf8, 0xd1, 0xb6, 0xc4, 0x2c, 0x13, 0x73,
	0x3d, 0xcb, 0x89, 0xdc, 0x89, 0xd9, 0xb8, 0x79, 0xdf, 0x2c, 0x97, 0xce, 0x64, 0xed, 0x6c, 0xbe,
	0xe5, 0x00, 0xa7, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0x0c, 0x5f, 0x29, 0x0f, 0x01, 0x00,
	0x00,
}
