// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetStudentsResponse struct {
	Success              bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Students             []*Student `protobuf:"bytes,3,rep,name=students,proto3" json:"students,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetStudentsResponse) Reset()         { *m = GetStudentsResponse{} }
func (m *GetStudentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetStudentsResponse) ProtoMessage()    {}
func (*GetStudentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{0}
}

func (m *GetStudentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudentsResponse.Unmarshal(m, b)
}
func (m *GetStudentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudentsResponse.Marshal(b, m, deterministic)
}
func (m *GetStudentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentsResponse.Merge(m, src)
}
func (m *GetStudentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetStudentsResponse.Size(m)
}
func (m *GetStudentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentsResponse proto.InternalMessageInfo

func (m *GetStudentsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetStudentsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetStudentsResponse) GetStudents() []*Student {
	if m != nil {
		return m.Students
	}
	return nil
}

type Student struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{1}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*GetStudentsResponse)(nil), "pb.GetStudentsResponse")
	proto.RegisterType((*Student)(nil), "pb.Student")
}

func init() { proto.RegisterFile("student.proto", fileDescriptor_94a1c1b032ad0c00) }

var fileDescriptor_94a1c1b032ad0c00 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xbf, 0x0e, 0x82, 0x30,
	0x10, 0x87, 0x43, 0x51, 0x81, 0x23, 0x3a, 0x9c, 0x0e, 0x1d, 0x09, 0x8b, 0x4c, 0x0c, 0xfa, 0x08,
	0x0e, 0xee, 0xf5, 0x09, 0xf8, 0x73, 0x31, 0x24, 0xd2, 0x36, 0x5c, 0x79, 0x7f, 0x63, 0x69, 0xdd,
	0xfa, 0x7d, 0xbf, 0xe4, 0x6b, 0x0e, 0x8e, 0xec, 0xd6, 0x91, 0xb4, 0x6b, 0xed, 0x62, 0x9c, 0x41,
	0x61, 0xfb, 0x7a, 0x81, 0xf3, 0x93, 0xdc, 0x6b, 0xf3, 0xac, 0x88, 0xad, 0xd1, 0x4c, 0x28, 0x21,
	0xe3, 0x75, 0x18, 0x88, 0x59, 0x26, 0x55, 0xd2, 0xe4, 0x2a, 0xe2, 0x6f, 0x99, 0x89, 0xb9, 0x7b,
	0x93, 0x14, 0x55, 0xd2, 0x14, 0x2a, 0x22, 0x5e, 0x21, 0x0f, 0x7d, 0x96, 0x69, 0x95, 0x36, 0xe5,
	0xad, 0x6c, 0x6d, 0xdf, 0x86, 0xb6, 0xfa, 0x8f, 0xf5, 0x03, 0xb2, 0x20, 0xf1, 0x04, 0x62, 0x1a,
	0xfd, 0x17, 0x85, 0x12, 0xd3, 0x88, 0x08, 0x3b, 0xdd, 0xcd, 0x31, 0xed, 0xdf, 0x78, 0x81, 0x3d,
	0xcd, 0xdd, 0xf4, 0x91, 0xa9, 0x97, 0x1b, 0xf4, 0x07, 0x7f, 0xc3, 0xfd, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x3c, 0xb5, 0x0b, 0x13, 0xd4, 0x00, 0x00, 0x00,
}
