[cockroach]
Host        = "roach1"
Port        = "26257"
Password    = "root"
User        = "root"
Database    = "defaultdb"

[nats]
URI         = "nats://nats:4222"
User        = "product"
Password    = "gopher"
Queue       = "PERSIST-STUDENT"
Name        = "Nats Responder"
WaitTimeInMinutes = 10